// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Explains a complex topic by providing a clear explanation, examples, and analogies.
 *
 * - explainTopic - A function that takes a topic as input and returns a clear explanation, examples, and an analogy.
 * - ExplainTopicInput - The input type for the explainTopic function.
 * - ExplainTopicOutput - The return type for the explainTopic function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainTopicInputSchema = z.object({
  topic: z.string().describe('The topic to explain.'),
});
export type ExplainTopicInput = z.infer<typeof ExplainTopicInputSchema>;

const ExplainTopicOutputSchema = z.object({
  explanation: z.string().describe('A clear and concise explanation of the topic.'),
  examples: z.string().describe('A list of examples related to the topic.'),
  analogy: z.string().describe('A simple analogy to help understand the topic.'),
});
export type ExplainTopicOutput = z.infer<typeof ExplainTopicOutputSchema>;

export async function explainTopic(input: ExplainTopicInput): Promise<ExplainTopicOutput> {
  return explainTopicFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainTopicPrompt',
  input: {schema: ExplainTopicInputSchema},
  output: {schema: ExplainTopicOutputSchema},
  prompt: `You are an expert in explaining complex topics in a simple and understandable way.

  Topic: {{{topic}}}

  Provide the following:
  1. A clear and concise explanation of the topic.
  2. A list of examples related to the topic.
  3. A simple analogy to help understand the topic.

  Format your answer as follows:

  Explanation: <explanation>
  Examples: <examples>
  Analogy: <analogy>`,
});

const explainTopicFlow = ai.defineFlow(
  {
    name: 'explainTopicFlow',
    inputSchema: ExplainTopicInputSchema,
    outputSchema: ExplainTopicOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
