"use client";

import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { ScrollArea } from '@/components/ui/scroll-area';

export function PrivacyPolicy() {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="link" className="w-full">Privacy Policy</Button>
      </SheetTrigger>
      <SheetContent className="flex flex-col">
        <SheetHeader>
          <SheetTitle>Privacy Policy</SheetTitle>
        </SheetHeader>
        <ScrollArea className="flex-1 mt-4 -mx-6">
          <div className="px-6 prose prose-sm dark:prose-invert max-w-none">
            <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>

            <p>
              Welcome to Clarity AI. This Privacy Policy explains how we handle your information when you use our application. Your privacy is critically important to us.
            </p>

            <h3>1. Information We Do Not Collect</h3>
            <p>
              Clarity AI is designed with privacy as a core principle. We do not collect, store, transmit, or have access to any of your personal data on our servers.
            </p>

            <h3>2. Local Storage</h3>
            <p>
              All data generated by the application, including your chat history, AI settings (persona and language), and other preferences, is stored exclusively on your local device using your web browser's `localStorage` functionality. This data remains in your browser and is not sent to any remote server controlled by us.
            </p>

            <h3>3. Third-Party Services (AI Provider)</h3>
            <p>
              Our application uses Google AI (via Genkit) to provide its intelligent features. When you interact with the AI (e.g., send a message, request a summary), the relevant data (such as your message content, chat history, and selected persona/language) is sent to Google's servers to generate a response. We do not log or store this data on our end. We encourage you to review Google's Privacy Policy to understand how they handle data.
            </p>

            <h3>4. Data Deletion</h3>
            <p>
              You have full control over your data. You can delete individual chat sessions from within the application's settings panel. To delete all application data, you can clear your browser's cache and site data for this application's domain.
            </p>

            <h3>5. Changes to This Privacy Policy</h3>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy within the application. You are advised to review this Privacy Policy periodically for any changes.
            </p>

            <h3>6. Contact Us</h3>
            <p>
              If you have any questions about this Privacy Policy, you can contact us by email: <a href="mailto:nextgendeveloperalihassan@gmail.com" className="text-primary underline">nextgendeveloperalihassan@gmail.com</a>
            </p>
          </div>
        </ScrollArea>
      </SheetContent>
    </Sheet>
  );
}
